# Site settings
title: Personal blog of Michael Kühnel
email: mail@michael-kuehnel.de
description: Michael Kühnel, Front-End Developer from Kassel blogging about Markup, CSS, JavaScript and related stuff. English/German.
baseurl: ""
url: "http://michael-kuehnel.de"
twitter_username: mkuehnel
github_username: mischah

# Build settings
markdown: kramdown
kramdown:
  input: GFM
