# Site settings
title: Michael Kühnel
email: mail@michael-kuehnel.de
description: > # this means to ignore newlines until "baseurl:"
  Michael Kühnel, Front-End Developer from Kassel, Germany – blogging about
  Markup, CSS, JavaScript and related stuff. Sometimes in English and sometimes
  in German.
baseurl: ""
url: "http://michael-kuehnel.de"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
